CREATE TABLE IF NOT EXISTS sessions (
    userId TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiresAt DATETIME NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);

